[pytest]
pythonpath = src/
markers =
    entity: Marca testes relacionados a extração de entidades
    dados_bancarios: Testes relacionados à entidade DADOS_BANCARIOS
    cep: Testes relacionados à entidade CEP
    cnh: Testes relacionados à entidade CNH
    cpf: Testes relacionados à entidade CPF
    email: Testes relacionados à entidade EMAIL
    endereco: Testes relacionados à entidade ENDERECO
    fistel: Testes relacionados à entidade FISTEL
    data_nascimento: Testes relacionados à entidade DATA_NASCIMENTO
    passaporte: Testes relacionados à entidade PASSAPORTE
    rg: Testes relacionados à entidade RG
    siape: Testes relacionados à entidade SIAPE
    telefone: Testes relacionados à entidade TELEFONE
    titulo_eleitor: Testes relacionados à entidade TITULO_ELEITOR