[metadata]
name = anonimizador-dp
version = 0.10.0
author = Anatel
author_email = seiia@anatel.gov.br
description = Anonimizador de dados pessoais (PII) em português brasileiro.
long_description = file: README.md
long_description_content_type = text/markdown
# url = https://git.anatel.gov.br/processo_eletronico/sei-ia/sei-anonimizar
# project_urls =
#     Homepage = https://git.anatel.gov.br/processo_eletronico/sei-ia/sei-anonimizar
license = GPL-3.0-only
license_files = LICENSE*
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent

[options]
python_requires = >=3.10
install_requires =
    spacy==3.8.4
    python-dotenv==1.2.2
    scikit-learn==1.7.2
packages = find:
include_package_data = True

[options.extras_require]
dev =
    pytest==9.0.3
    ruff==0.11.6

[options.packages.find]
where = src
include =
    anonimizar*
    anonimizar.*
exclude =
    tests*
    docs*
    examples*
    docker*
    notebooks*
